name: Production Deploy
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  packages: write
jobs:
  ubuntu:
    strategy:
      matrix:
        version:
          - latest

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ubuntu-${{ matrix.version }}:v${{ github.run_number }}
            ghcr.io/${{ github.repository_owner }}/ubuntu-${{ matrix.version }}:latest
          path: ansible/${{ matrix.version }}/Dockerfile
          push: true
          cache: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ubuntu-${{ matrix.version }}:buildcache

  ansible:
    strategy:
      matrix:
        version:
          - latest

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ansible-${{ matrix.version }}:v${{ github.run_number }}
            ghcr.io/${{ github.repository_owner }}/ansible-${{ matrix.version }}:latest
          path: ansible/${{ matrix.version }}/Dockerfile
          push: true
          cache: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ansible-${{ matrix.version }}:buildcache
