name: Production Deploy
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  packages: write
jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      ansible: ${{ steps.path-filter.outputs.ansible }}
      ubuntu: ${{ steps.path-filter.outputs.ubuntu }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: path-filter
        with:
          filters: |
            ansible:
              - "ansible/**"
              - ".github/workflows/ci.yaml"
              - ".github/actions/**"
            ubuntu:
              - "ubuntu/**"
              - ".github/workflows/ci.yaml"
              - ".github/actions/**"

  ubuntu:
    needs: filter
    if: needs.filter.outputs.ubuntu == 'true'
    strategy:
      matrix:
        version:
          - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ubuntu-${{ matrix.version }}:v${{ github.run_number }}
            ghcr.io/${{ github.repository_owner }}/ubuntu-${{ matrix.version }}:latest
          path: ansible/${{ matrix.version }}
          push: true
          cache: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ubuntu-${{ matrix.version }}:buildcache

  ansible:
    needs: filter
    if: needs.filter.outputs.ansible == 'true'
    strategy:
      matrix:
        version:
          - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ansible-${{ matrix.version }}:v${{ github.run_number }}
            ghcr.io/${{ github.repository_owner }}/ansible-${{ matrix.version }}:latest
          path: ansible/${{ matrix.version }}
          push: true
          cache: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ansible-${{ matrix.version }}:buildcache
