name: Production Deploy
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  packages: write
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu
        version:
          - latest

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ matrix.os }}/${{ matrix.version }}
          file: ${{ matrix.os }}/${{ matrix.version }}/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.os }}:${{ matrix.version }}-${{ github.run_number }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}-${{ matrix.os }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}-${{ matrix.os }}:buildcache,mode=max
