name: CI
on:
  pull_request:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu
          - ansible
        version:
          - latest

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: false
          context: ${{ matrix.os }}/${{ matrix.version }}
          file: ${{ matrix.os }}/${{ matrix.version }}/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.os }}-${{ matrix.version }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha
