name: CI
on:
  pull_request:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  ubuntu:
    strategy:
      matrix:
        version:
          - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ubuntu-${{ matrix.version }}:${{ github.sha }}
          path: ubuntu/${{ matrix.version }}
          cache: type=gha
        
  ansible:
    strategy:
      matrix:
        version:
          - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ansible-${{ matrix.version }}:${{ github.sha }}
          path: ansible/${{ matrix.version }}
          push: false
          cache: type=gha
